"""empty message

Revision ID: 168db597b4da
Revises: 6cfa294c06c7
Create Date: 2020-10-06 16:03:38.960125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '168db597b4da'
down_revision = '6cfa294c06c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=254), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
