"""fix ImageModel

Revision ID: 24da1d2ec47c
Revises: 7dd3fb5ae618
Create Date: 2020-11-28 20:33:29.742445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24da1d2ec47c'
down_revision = '7dd3fb5ae618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_model', sa.Column('filename', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_model', 'filename')
    # ### end Alembic commands ###
