"""campos adicionales para foto

Revision ID: 267ae80975c3
Revises: 98c159be65de
Create Date: 2020-12-23 20:24:03.475798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '267ae80975c3'
down_revision = '98c159be65de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('camera', sa.String(length=100), nullable=True))
    op.add_column('photo', sa.Column('fnumber', sa.Float(), nullable=True))
    op.add_column('photo', sa.Column('focal', sa.Integer(), nullable=True))
    op.add_column('photo', sa.Column('isovalue', sa.Integer(), nullable=True))
    op.add_column('photo', sa.Column('software', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'software')
    op.drop_column('photo', 'isovalue')
    op.drop_column('photo', 'focal')
    op.drop_column('photo', 'fnumber')
    op.drop_column('photo', 'camera')
    # ### end Alembic commands ###
