"""add article fields

Revision ID: 4744b6b5da4c
Revises: c4876f7ffd6e
Create Date: 2020-11-17 21:38:48.706454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4744b6b5da4c'
down_revision = 'c4876f7ffd6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('author_id', sa.String(length=32), nullable=True))
    op.add_column('article', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('article', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('article', sa.Column('credit_line', sa.String(length=160), nullable=True))
    op.add_column('article', sa.Column('excerpt', sa.Text(), nullable=True))
    op.create_index(op.f('ix_article_created_on'), 'article', ['created_on'], unique=False)
    op.create_foreign_key(None, 'article', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_index(op.f('ix_article_created_on'), table_name='article')
    op.drop_column('article', 'excerpt')
    op.drop_column('article', 'credit_line')
    op.drop_column('article', 'created_on')
    op.drop_column('article', 'content')
    op.drop_column('article', 'author_id')
    # ### end Alembic commands ###
