"""Add other fields to photo model

Revision ID: 5745d0b94cfe
Revises: e883c6fdc99a
Create Date: 2020-12-05 16:04:35.932714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5745d0b94cfe'
down_revision = 'e883c6fdc99a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('credit_line', sa.String(length=160), nullable=True))
    op.add_column('photo', sa.Column('excerpt', sa.Text(), nullable=True))
    op.add_column('photo_coverage', sa.Column('credit_line', sa.String(length=160), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo_coverage', 'credit_line')
    op.drop_column('photo', 'excerpt')
    op.drop_column('photo', 'credit_line')
    # ### end Alembic commands ###
