"""agrega ImageModel

Revision ID: 7dd3fb5ae618
Revises: 4744b6b5da4c
Create Date: 2020-11-28 19:45:13.148342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dd3fb5ae618'
down_revision = '4744b6b5da4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_model',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('upload_by', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['upload_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_model')
    # ### end Alembic commands ###
