"""agregar campo excerpt a Photo

Revision ID: 98c159be65de
Revises: 5745d0b94cfe
Create Date: 2020-12-10 18:46:29.672655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98c159be65de'
down_revision = '5745d0b94cfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('headline', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'headline')
    # ### end Alembic commands ###
