"""agrega campo a ImageModel

Revision ID: b9c3738b23c7
Revises: f15cb00bdeb5
Create Date: 2021-01-14 21:23:34.036563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9c3738b23c7'
down_revision = 'f15cb00bdeb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_model', sa.Column('store_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_model', 'store_data')
    # ### end Alembic commands ###
