"""test article.keywords

Revision ID: c4876f7ffd6e
Revises: 3106edc24862
Create Date: 2020-11-17 17:15:05.344759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4876f7ffd6e'
down_revision = '3106edc24862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('headline', sa.String(length=512), nullable=True))
    op.add_column('article', sa.Column('keywords', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'keywords')
    op.drop_column('article', 'headline')
    # ### end Alembic commands ###
