"""PhotoStore models

Revision ID: e883c6fdc99a
Revises: 24da1d2ec47c
Create Date: 2020-12-04 16:36:22.832386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e883c6fdc99a'
down_revision = '24da1d2ec47c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('capacity', sa.BigInteger(), nullable=True),
    sa.Column('used', sa.BigInteger(), nullable=True),
    sa.Column('fspath', sa.Text(), nullable=True),
    sa.Column('is_full', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('capacity', sa.BigInteger(), nullable=True),
    sa.Column('used', sa.BigInteger(), nullable=True),
    sa.Column('fspath', sa.Text(), nullable=True),
    sa.Column('is_full', sa.Boolean(), nullable=True),
    sa.Column('is_burned', sa.Boolean(), nullable=True),
    sa.Column('volume_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['volume_id'], ['volume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo_coverage',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('headline', sa.String(length=512), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('author_id', sa.String(length=32), nullable=True),
    sa.Column('archive_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_coverage_archive_on'), 'photo_coverage', ['archive_on'], unique=False)
    op.create_table('photo',
    sa.Column('md5', sa.String(length=32), nullable=False),
    sa.Column('fspath', sa.Text(), nullable=True),
    sa.Column('thumbnail', sa.Text(), nullable=True),
    sa.Column('archive_on', sa.DateTime(), nullable=True),
    sa.Column('taken_on', sa.DateTime(), nullable=True),
    sa.Column('taken_by', sa.String(length=100), nullable=True),
    sa.Column('exif_info', sa.Text(), nullable=True),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('upload_by', sa.String(length=32), nullable=True),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['upload_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('md5')
    )
    op.create_index(op.f('ix_photo_archive_on'), 'photo', ['archive_on'], unique=False)
    op.create_index(op.f('ix_photo_taken_on'), 'photo', ['taken_on'], unique=False)
    op.create_table('photo_galley',
    sa.Column('photo_coverage_id', sa.String(length=32), nullable=False),
    sa.Column('photo_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['photo_coverage_id'], ['photo_coverage.id'], ),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.md5'], ),
    sa.PrimaryKeyConstraint('photo_coverage_id', 'photo_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo_galley')
    op.drop_index(op.f('ix_photo_taken_on'), table_name='photo')
    op.drop_index(op.f('ix_photo_archive_on'), table_name='photo')
    op.drop_table('photo')
    op.drop_index(op.f('ix_photo_coverage_archive_on'), table_name='photo_coverage')
    op.drop_table('photo_coverage')
    op.drop_table('media')
    op.drop_table('volume')
    # ### end Alembic commands ###
