"""agrega tabla de permisos

Revision ID: efb9cf4605ed
Revises: f148d5ea99a0
Create Date: 2020-10-26 20:41:16.802637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efb9cf4605ed'
down_revision = 'f148d5ea99a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('model_name', sa.String(length=80), nullable=True),
    sa.Column('record_id', sa.String(length=32), nullable=True),
    sa.Column('role_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permission')
    # ### end Alembic commands ###
