version: '3'

services: 

    database:
        image: mysql
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: sjBf743/dJk
            MYSQL_DATABASE: authdb
            MYSQL_USER: authdb
            MYSQL_PASSWORD: f9mqwdNJuqSJFSqT
        volumes:
            - ./database:/var/lib/mysql

    redis:
        image: redis
    
    app:
        build: ./app
        restart: always
        depends_on: 
            - database
            - redis
        command: gunicorn "application:create_app('config.Config')" --log-level=debug --reload -b 0.0.0.0:5000
        environment: 
            SECRET_KEY: sjBf743/dJkaut3hdbf9mqwdNJuqSJ4413mdnduhrFSqT
            SQLALCHEMY_DATABASE_URI: mysql+pymysql://authdb:f9mqwdNJuqSJFSqT@database/authdb
            FLASK_APP: application:create_app('config.Config')
            UPLOAD_FOLDER: "/uploads"
            # comentar si no son necesarios
            HTTP_PROXY: "http://192.168.2.2:3128"
            HTTPS_PROXY: "http://192.168.2.2:3128"
            FTP_PROXY: "http://192.168.2.2:3128"
            NO_PROXY: "intranet.adelante.lan,*.adelante.lan,.adelante.lan"
            http_proxy: "http://192.168.2.2:3128"
            https_proxy: "http://192.168.2.2:3128"
            ftp_proxy: "http://192.168.2.2:3128"
            no_proxy: "intranet.adelante.lan,*.adelante.lan,.adelante.lan"
            DEFAULT_VOL_SIZE: 107374182400
            DEFAULT_MEDIA_SIZE: 4831838208
        expose: 
            - 5000
        volumes:
            - ./app:/src
            - ./uploads:/uploads
        extra_hosts:
            - "intranet.adelante.lan:192.168.2.2"

    web:
        build: ./nginx
        restart: always
        environment: 
            AUTH_ENDPOINT: app.local
        ports: 
            - 8080:8080
        depends_on: 
            - app

